### ISSUE TITLE
Reduce package dependencies

### ISSUE THREAD

**Issue by psychelzh** [daranzolin/sqltargets#9]
The following recommendations:

* **RSQLite**: move this to Suggests?
* **readr**: there is only one call of `readr::read_lines()`, so it will be better to use `readLines()` in base instead.

**Comment by daranzolin** [comment]
Agreed. Will make the changes for the next release.

**Comment by daranzolin** [comment]
Closed in https://github.com/daranzolin/sqltargets/commit/981cabca1b2d73ce3e885d63353d1c59bf4fadd4
